/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.internal;

import controller.CustomerController;
import controller.OrderController;
import controller.Tools;
import java.awt.Frame;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import view.HtmlReport;

/**
 *
 * @author sandakelum
 */
public class GenerateOrderReport extends javax.swing.JInternalFrame {

    /**
     * Creates new form GenerateOrderReport
     */
    public GenerateOrderReport() {
        initComponents();

        dateFrom.setDateFormatString("yyyy/MM/dd");
        dateFrom.setDate(new Date());

        dateTo.setDateFormatString("yyyy/MM/dd");
        dateTo.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateFrom = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateTo = new com.toedter.calendar.JDateChooser();
        btnGenerate = new javax.swing.JButton();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(31, 161, 240), 1, true));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Generate order report");

        jLabel1.setText("from");

        jLabel2.setText("to");

        btnGenerate.setBackground(new java.awt.Color(1, 84, 254));
        btnGenerate.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerate.setText("Generate");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(dateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnGenerate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateTo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnGenerate)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        OrderController oc = new OrderController();
        CustomerController cc = new CustomerController();
        Tools tools = new Tools();
        DateFormat df = new SimpleDateFormat("yyyy/MM/dd");
        try {
            String strHtml = "<html>"
                    + "<head><meta name='viewport' content='width=device-width', initial-scale=1.0'>"
                    + "<style>"
                    + "body{"
                    + "font-family:arial;"
                    + "}"
                    + ".rhead{background-color:#001e6c; }"
                    + ".col-head{background-color:#035397;}"
                    + ".wh{color:#ffffff;}"
                    + "</style>"
                    + "</head>"
                    + "<body>"
                    + "<table style='width:100%' >"
                    + "<tr class='rhead' ><th colspan='4'><h1 class='wh' >Order Report</h1></th></tr>"
                    + "<tr><th>"+df.format(dateFrom.getDate()).toString()+" to "+df.format(dateTo.getDate()).toString()+"</th></tr>"
                    + "<tbody style='font-size:13px;' ><tr class='col-head' >"
                    + "<td class='wh' ><b>Order Ref</b></td>"
                    + "<td class='wh'><b>Customer Name</b></td>"
                    + "<td class='wh'><b>Date</b></td>"
                    + "<td class='wh'><b>Price</b></td></tr>";
            
            
            ResultSet r = oc.loadOrdersBetweenDate(df.format(dateFrom.getDate()).toString(),df.format(dateTo.getDate()).toString());
            float tot = 0;
            while (r.next()) {
                String trow = "<tr>"
                        + "<td>" + r.getString("randId") + "</td>"
                        + "<td>" + cc.getCutomerNameById(r.getInt("customerId")) + "</td>"
                        + "<td>" + r.getString("date") + "</td>"
                        + "<td>" + r.getFloat("price") + "</td>"
                        + "</tr>";
                tot = tot + r.getFloat("price");
                strHtml = strHtml + trow;
            }
            strHtml = strHtml + "<td></td><td></td><td></td><td style='color:blue;'>"+tot+"</td>"
                    + "</tbody></table></body></html>";
            
            HtmlReport hr = new HtmlReport((Frame) tools.getVisibleContent(),true);
            hr.setLocationRelativeTo(tools.getVisibleContent());
            hr.loadHtml(strHtml);
            hr.setVisible(true);
            
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnGenerateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerate;
    private com.toedter.calendar.JDateChooser dateFrom;
    private com.toedter.calendar.JDateChooser dateTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
