/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.internal;

import controller.CustomerController;
import controller.ItemController;
import controller.OrderController;
import controller.OrderItemController;
import controller.Tools;
import java.awt.Frame;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import view.HtmlReport;

/**
 *
 * @author sandakelum
 */
public class ViewOrder extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewOrder
     */
    DefaultTableModel model;
    String selectedOr = "";

    public ViewOrder() {
        initComponents();
        loadData();

    }

    private void loadData() {

        loadTable();

    }

    private void loadTable() {
        try {
            OrderController oc = new OrderController();
            CustomerController cc = new CustomerController();
            ResultSet r = oc.loadOrders();

            model = (DefaultTableModel) tblOrder.getModel();
            model.setRowCount(0);
            while (r.next()) {
                Vector v = new Vector();
                v.add(r.getString("randId"));
                v.add(cc.getCutomerNameById(Integer.parseInt(r.getString("customerId"))).equals("") ? "Deleted Customer" : cc.getCutomerNameById(Integer.parseInt(r.getString("customerId"))));
                v.add(r.getString("date"));
                v.add(r.getFloat("price"));
                model.addRow(v);
            }

            tblOrder.setModel(model);

        } catch (Exception e) {
        }

    }

    private void searchOrder(String data) {

        try {
            OrderController oc = new OrderController();
            CustomerController cc = new CustomerController();
            ResultSet r = oc.searchOrdersByCustomerName(data);

            model = (DefaultTableModel) tblOrder.getModel();
            model.setRowCount(0);
            while (r.next()) {
                Vector v = new Vector();
                v.add(r.getString("randId"));
                v.add(cc.getCutomerNameById(Integer.parseInt(r.getString("customerId"))));
                v.add(r.getString("date"));
                v.add(r.getFloat("price"));
                model.addRow(v);
            }

            tblOrder.setModel(model);

        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        txtSearchBox = new javax.swing.JTextField();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(31, 161, 240), 1, true));
        setClosable(true);
        setIconifiable(true);
        setTitle("View Orders");

        jLabel1.setFont(new java.awt.Font("Monaco", 1, 13)); // NOI18N
        jLabel1.setText("Search by customer name");

        btnView.setBackground(new java.awt.Color(1, 84, 254));
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("View Selected");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Order Table");

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Ref", "Customer name", "Date", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblOrderMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrder);

        btnDelete.setBackground(new java.awt.Color(218, 57, 57));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete Selected");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        txtSearchBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchBoxKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSearchBox)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh)
                    .addComponent(btnView)
                    .addComponent(btnDelete))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadTable();

    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtSearchBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchBoxKeyReleased
        searchOrder(txtSearchBox.getText());
    }//GEN-LAST:event_txtSearchBoxKeyReleased

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (!selectedOr.equals("")) {
            OrderController oc = new OrderController();
            oc.deleteOrders(selectedOr);
            loadTable();
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblOrderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrderMousePressed
        int row = tblOrder.getSelectedRow();
        selectedOr = tblOrder.getModel().getValueAt(row, 0).toString();

    }//GEN-LAST:event_tblOrderMousePressed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        OrderItemController oic = new OrderItemController();
        ItemController ic = new ItemController();
        String or = "", d = "", tot = "";

        try {

            if (!selectedOr.equals("")) {
                or = selectedOr;
                int row = tblOrder.getSelectedRow();
                d = tblOrder.getModel().getValueAt(row, 2).toString();
                tot = tblOrder.getModel().getValueAt(row, 3).toString();
                Tools tool = new Tools();
                String strhtml = "<html>"
                        + "<head><meta name='viewport' content='width=device-width', initial-scale=1.0'>"
                        + "<style>"
                        + "body{"
                        + "font-family:arial;"
                        + "}"
                        + ".rhead{background-color:#001e6c; }"
                        + ".col-head{background-color:#035397;}"
                        + ".wh{color:#ffffff;}"
                        
                        + "</style>"
                        + "</head>"
                        + "<body>"
                        + "<table style='width:100%'>"
                        + "<tr class='rhead'><th colspan='3'><h1 class='wh' >INVOICE</h1></th><tr>"
                        + "<tr><td>Order Ref : " + or + "</td><td></td><td>Date :" + d
                        + "</td></tr></table><br><br>"
                        + "<table style='width:100%; font-size:13px;' >"                                              
                        + "<tr class='col-head'><td class='wh' ><b>Item Code</b></td>"
                        + "<td class='wh'><b>Quantity</b></td>"
                        + "<td class='wh'><b>Price</b></td></tr>";

                ResultSet r = oic.getOrderItemsByRef(or);

                while (r.next()) {
                    float p = ic.getItemPrice(r.getString("itemCode")) * r.getInt("quantity");
                    strhtml = strhtml + "<tr><td>"
                            + r.getString("itemCode") + "</td><td>"
                            + r.getInt("quantity") + "</td><td>"
                            + p + "</td></tr>";

                }

                strhtml = strhtml + "<tr><td></td><td></td><td style='color:blue;' >" + tot + " </td></tr></table></body></html>";

                HtmlReport hr = new HtmlReport((Frame) tool.getVisibleContent(), true);
                hr.setLocationRelativeTo((Frame) tool.getVisibleContent());
                hr.loadHtml(strhtml);
                hr.setVisible(true);

            }

        } catch (Exception e) {
        }


    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTextField txtSearchBox;
    // End of variables declaration//GEN-END:variables
}
